### ISSUE TITLE
The set-output command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by donfirst** [sanjP10/describe-cloudformation-change-sets#10]
Describe the feature

The ::set-output:: function is deprecated in favor of using the GITHUB_OUTPUT environment file

Use Case

The set-output function is insecure according to this notification: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Other Information

No response

# Additional context

**Comment by sanjP10** [comment]
@donfirst please can you double check on your end using sanjP10/describe-cloudformation-change-sets@UpdateSetEnv and let me know. Should have exactly the same functionality and work the same. For both has-changes and the results. Once confirmed I'll merge down

**Comment by donfirst** [comment]
@sanjP10 All works well .You can merge.Thank you  for your support

**Comment by sanjP10** [comment]
@donfirst merged
