### ISSUE TITLE
${{ steps.describe-change-set.outputs.has-changes }} always return true

### ISSUE THREAD

**Issue by donfirst** [sanjP10/describe-cloudformation-change-sets#8]
${{ steps.describe-change-set.outputs.has-changes }} always return true

### Prerequisites

* [ ] Are you running the latest version?
* [ ] Did you read through the instructions on the README?

# Describe the bug

# To Reproduce
Steps to reproduce the behaviour (including settings of aws permissions and action syntax used):

# Expected behaviour

# Screenshots

# Additional context

**Comment by sanjP10** [comment]
@donfirst can you try sanjP10/describe-cloudformation-change-sets@FixOutputsLogic and see if that has fixed the issue please. 

I've tested it but would be gd to check with you that it all works. Once done I will then merge and cut a release

**Comment by donfirst** [comment]
Yes IT works now :-)
You can  merge - thank you you for your help :-)

**Comment by sanjP10** [comment]
All merged and released
